-- 미션 목록 채우기 (2026-08-01) — 딥리서치 결과를 걸러서 넣는다
--
-- 거른 기준:
--   · 저학년 사진(review) 비중을 권고(20%)에 맞춤 — 원표는 45개 중 20개 넘게 사진이었다
--
-- ⚠ 처음엔 「불을 쓰는 것」과 「아이가 찍히는 사진」을 뺐다가 되돌렸다(2026-08-01 사장님 지적):
--   · 미션은 **부모가 고르는 것**이다. 위험하면 부모가 안 고르면 된다.
--     우리가 미리 빼면 그건 과보호를 강제하는 것이고, 6학년이 라면도 못 끓이는 게 오히려 문제다.
--     대신 caution 에 「불을 써요」를 달아 부모가 **알고** 고르게 한다.
--   · 비타민 먹는 사진·땀난 얼굴·물 주는 모습은 **부모가 보고 싶은 바로 그것**이다.
--     부모에게만 가고 7일 뒤 지워진다. 결과물만 찍게 바꿀 이유가 없었다.
--
-- 다시 돌려도 되게 만든다(DELETE 후 INSERT). 문구를 고치면 code 는 그대로 두고 title 만 바꾼다.

DELETE FROM missions;
DELETE FROM mission_banned;

-- ══════════ 초1~2 (45) ══════════
INSERT INTO missions (code,band,season,title,area,minutes,cycle,verify,verify_hint,slot,stars,why,created_at) VALUES
('L-W01','low','weekday','일어나서 물 한 컵 마시기','body',1,'daily','instant',NULL,'morning',1,'한 동작으로 끝나 실패할 수 없다','2026-08-01'),
('L-W02','low','weekday','자고 일어나 이불 펴기','things',2,'daily','review','펴놓은 이불','morning',1,'소근육이 미숙해 「개기」가 아니라 「펴기」가 맞다','2026-08-01'),
('L-W03','low','weekday','화장실 다녀와 손 씻기','body',2,'daily','instant',NULL,'any',1,'바른생활 성취기준의 기초 위생','2026-08-01'),
('L-W04','low','weekday','빈 그릇 싱크대에 놓기','family',1,'daily','instant',NULL,'evening',1,'가볍고 안 깨지는 것만 옮긴다','2026-08-01'),
('L-W05','low','weekday','벗은 겉옷 옷걸이에 걸기','things',1,'daily','review','걸려 있는 옷','after',1,'물건 제자리 찾기의 가장 쉬운 형태','2026-08-01'),
('L-W06','low','weekday','연필 세 자루 필통에 넣기','study',2,'daily','instant',NULL,'after',1,'개수가 정해져 있어 끝이 분명하다','2026-08-01'),
('L-W07','low','weekday','벗은 양말 빨래통에 넣기','things',1,'daily','instant',NULL,'after',1,'잔소리를 가장 많이 줄이는 한 동작','2026-08-01'),
('L-W08','low','weekday','가방 제자리에 놓기','things',1,'daily','instant',NULL,'after',1,'위치를 기억하는 공간 지각 훈련','2026-08-01'),
('L-W09','low','weekday','양치 삼 분 하기','body',3,'daily','instant','앱 타이머','any',1,'타이머가 끝을 보여줘 짧은 집중력을 보완한다','2026-08-01'),
('L-W10','low','weekday','알림장 식탁에 두기','study',1,'daily','instant',NULL,'after',1,'부모가 어차피 보게 되므로 사진이 필요 없다','2026-08-01'),
('L-W11','low','weekday','신발 바르게 놓기','outside',1,'daily','review','가지런한 내 신발','after',1,'결과가 눈에 바로 보이는 기초 습관','2026-08-01'),
('L-W12','low','weekday','빈 물통 가방에서 꺼내기','study',2,'daily','instant',NULL,'after',1,'혼자 끝낼 수 있는 아주 명확한 한 가지','2026-08-01'),
('L-W13','low','weekday','밥 먹고 식탁 닦기','family',3,'daily','instant',NULL,'evening',1,'단순한 몸놀림이라 가사 참여가 놀이가 된다','2026-08-01'),
('L-W14','low','weekday','머리 단정하게 빗기','body',2,'daily','instant',NULL,'morning',1,'내 몸을 챙긴다는 인식의 첫 단계','2026-08-01'),
('L-W15','low','weekday','의자에 오 분 앉아있기','study',5,'daily','instant','앱 타이머','after',2,'공부 내용이 아니라 앉는 것만 목표로 둔다','2026-08-01'),
('L-E01','low','weekend','장난감 통에 모으기','things',5,'weekly','review','정리된 장난감 통','any',2,'늘어지는 주말에 놀이의 끝을 맺는다','2026-08-01'),
('L-E02','low','weekend','어깨 삼 분 주무르기','family',3,'weekly','instant','앱 타이머','evening',1,'가족과 몸이 닿는 시간을 만든다','2026-08-01'),
('L-E03','low','weekend','실내화 가방 비우기','things',2,'weekly','instant',NULL,'morning',1,'주말이 시작됐다는 신호가 되는 절차','2026-08-01'),
('L-E04','low','weekend','내 수저 놓기','family',2,'weekly','instant',NULL,'evening',1,'가족 안에서 맡는 가장 작은 몫','2026-08-01'),
('L-E05','low','weekend','종이 분리수거함에 넣기','family',2,'weekly','instant',NULL,'any',1,'위험한 것이 없는 가장 쉬운 분리수거','2026-08-01'),
('L-E06','low','weekend','화분에 물 주기','family',3,'weekly','review','물 주는 모습','any',1,'살아 있는 것을 규칙적으로 돌본다','2026-08-01'),
('L-E07','low','weekend','내일 입을 옷 꺼내두기','things',5,'weekly','review','꺼내둔 옷','evening',2,'월요일 아침의 실랑이를 미리 없앤다','2026-08-01'),
('L-E08','low','weekend','현관 신발 모두 정리','family',5,'weekly','review','정리된 현관','any',2,'내 것이 아닌 것까지 돌보는 첫 걸음','2026-08-01'),
('L-E09','low','weekend','내 가방 젖은 곳 닦기','things',5,'weekly','instant',NULL,'any',2,'주말 시간을 써서 내 물건을 손본다','2026-08-01'),
('L-E10','low','weekend','좋아하는 그림책 꺼내오기','study',2,'weekly','instant',NULL,'any',1,'읽으라 하지 않고 책과 가까워지게만 한다','2026-08-01'),
('L-E11','low','weekend','양말 짝 맞춰 세 켤레 접기','family',5,'weekly','instant',NULL,'any',2,'같은 것을 찾는 분류 놀이가 된다','2026-08-01'),
('L-E12','low','weekend','가족과 십 분 걷기','outside',10,'weekly','instant','앱 타이머','any',2,'주말에 몸을 안 쓰는 것을 막는다','2026-08-01'),
('L-E13','low','weekend','이웃 만나면 인사하기','outside',1,'weekly','instant',NULL,'any',1,'바깥에서 맺는 가장 기초적인 관계','2026-08-01'),
('L-E14','low','weekend','샤워할 때 내 몸 직접 닦기','body',10,'weekly','instant',NULL,'evening',2,'부모 손을 빌리지 않는 첫 자립','2026-08-01'),
('L-E15','low','weekend','거실에 굴러다니는 물건 줍기','family',5,'weekly','review','모아둔 물건','any',2,'놀이처럼 참여하는 공용 공간 정리','2026-08-01'),
('L-V01','low','vacation','오전 열 시 전에 일어나기','body',0,'daily','instant','아침에 앱 켜기','morning',1,'방학에 무너지는 수면 리듬의 마지노선','2026-08-01'),
('L-V02','low','vacation','점심 먹고 바로 양치하기','body',3,'daily','instant','앱 타이머','any',1,'급식 시간이 없어져 흐트러지는 위생','2026-08-01'),
('L-V03','low','vacation','하루 한 번 비타민 먹기','body',1,'daily','review','비타민 먹는 모습','any',1,'내 건강을 내가 챙긴다는 감각','2026-08-01'),
('L-V04','low','vacation','오전에 유튜브 안 보기','digital',240,'daily','endday',NULL,'morning',3,'눈뜨자마자 영상으로 가는 것을 막는다','2026-08-01'),
('L-V05','low','vacation','창문 열어 환기하기','family',1,'daily','instant',NULL,'morning',1,'집에 오래 있는 만큼 집에 기여한다','2026-08-01'),
('L-V06','low','vacation','방학 숙제 한 쪽 풀기','study',5,'daily','review','푼 숙제 한 쪽','any',2,'분량이 아니라 매일 펴는 것에 목표를 둔다','2026-08-01'),
('L-V07','low','vacation','내 컵 식탁에 가져가기','family',1,'daily','instant',NULL,'any',1,'집밥이 늘어난 만큼 상차림에 참여','2026-08-01'),
('L-V08','low','vacation','놀고 와서 외투 털기','outside',2,'daily','instant',NULL,'after',1,'집에 오래 머무는 시기의 위생 습관','2026-08-01'),
('L-V09','low','vacation','안 쓰는 물건 하루 하나 버리기','things',3,'daily','review','버릴 물건','any',1,'방학 동안 내 공간을 조금씩 비운다','2026-08-01'),
('L-V10','low','vacation','밤 아홉 시 전에 눕기','body',0,'daily','endday',NULL,'evening',1,'밤이 늘어지는 것을 막는 잠자리 신호','2026-08-01'),
('L-P01','low','patience','간식 먹기 전 삼 분 기다리기','mind',3,'daily','instant','앱 타이머','any',1,'눈앞의 것을 참는 가장 기본적인 훈련','2026-08-01'),
('L-P02','low','patience','어른 통화 끝날 때까지 조용히','mind',5,'daily','instant',NULL,'any',2,'남의 상황을 보고 내 말을 미룬다','2026-08-01'),
('L-P03','low','patience','친구 말 끝까지 듣기','mind',2,'daily','instant',NULL,'any',1,'말을 끊지 않는 것으로 배우는 참을성','2026-08-01'),
('L-P04','low','patience','닫힘 버튼 안 누르기','outside',1,'daily','instant',NULL,'any',1,'누르고 싶은 충동을 알아차리고 멈춘다','2026-08-01'),
('L-P05','low','patience','나갈 때 문 앞에서 기다리기','outside',2,'daily','instant',NULL,'any',1,'뛰쳐나가는 충동을 막아 안전도 지킨다','2026-08-01');

-- ══════════ 초3~4 (45) ══════════
INSERT INTO missions (code,band,season,title,area,minutes,cycle,verify,verify_hint,slot,stars,why,created_at) VALUES
('M-W01','mid','weekday','알림장 보고 준비물 챙기기','study',5,'daily','review','가방과 준비물','after',2,'읽고 챙기는 두 단계를 소화할 수 있다','2026-08-01'),
('M-W02','mid','weekday','책상 위 치우기','things',5,'daily','review','정리된 책상','after',2,'공부할 자리를 스스로 만든다','2026-08-01'),
('M-W03','mid','weekday','숙제 오 분 시작하기','study',5,'daily','instant','앱 타이머','after',2,'정답이 아니라 시작에 보상을 준다','2026-08-01'),
('M-W04','mid','weekday','내 방 쓰레기통 비우기','things',3,'daily','instant',NULL,'after',1,'내 공간을 내가 맡는다는 인식이 생길 때','2026-08-01'),
('M-W05','mid','weekday','갠 빨래 내 서랍에 넣기','family',5,'weekly','review','서랍 속 옷','any',2,'옷 종류를 나누는 분류 능력이 자란다','2026-08-01'),
('M-W06','mid','weekday','자기 전 폰 거실에 두기','digital',0,'daily','endday',NULL,'evening',1,'스스로 멈추는 힘이 생길 때 규칙으로 굳힌다','2026-08-01'),
('M-W07','mid','weekday','일기 세 줄 쓰기','study',10,'daily','review','세 줄 쓴 노트','evening',2,'하루를 돌아보는 힘을 기른다','2026-08-01'),
('M-W08','mid','weekday','아침 여덟 시 전에 일어나기','body',0,'daily','instant','아침에 앱 켜기','morning',1,'시계를 보고 스스로 움직인다','2026-08-01'),
('M-W09','mid','weekday','겉옷 옷걸이에 바르게 걸기','things',2,'daily','instant',NULL,'after',1,'구겨지는 것을 알아채고 관리한다','2026-08-01'),
('M-W10','mid','weekday','샤워 후 화장실 정리하기','family',3,'daily','review','물기 없는 바닥','evening',1,'같이 쓰는 곳을 배려한다','2026-08-01'),
('M-W11','mid','weekday','날씨 보고 내일 옷 고르기','things',5,'daily','review','골라둔 옷','evening',2,'바깥 정보를 보고 스스로 정한다','2026-08-01'),
('M-W12','mid','weekday','책 십오 분 자리 지키기','study',15,'daily','instant','앱 타이머','any',3,'권수가 아니라 앉아 있는 시간만 잰다','2026-08-01'),
('M-W13','mid','weekday','나올 때 방 불 끄기','things',1,'daily','instant',NULL,'any',1,'아끼는 것을 몸에 익힌다','2026-08-01'),
('M-W14','mid','weekday','가방 속 쓰레기 버리기','things',3,'daily','instant',NULL,'after',1,'내 가방 속을 스스로 점검한다','2026-08-01'),
('M-W15','mid','weekday','연필 세 자루 미리 깎기','study',5,'daily','review','깎인 연필','evening',2,'손끝을 쓰는 힘이 붙어 미리 준비할 수 있다','2026-08-01'),
('M-E01','mid','weekend','수건 반듯하게 개기','family',10,'weekly','review','갠 수건','any',2,'같은 동작을 반복하며 참을성이 붙는다','2026-08-01'),
('M-E02','mid','weekend','실내화 빨기','things',15,'weekly','review','젖은 실내화','any',3,'시간이 걸리는 일을 해내며 보상의 값을 안다','2026-08-01'),
('M-E03','mid','weekend','플라스틱 라벨 떼기','family',10,'weekly','review','벗긴 라벨','any',2,'환경에 보탬이 된다는 실감','2026-08-01'),
('M-E04','mid','weekend','한 시간 스스로 놀기','mind',60,'weekly','instant','앱 타이머','any',3,'놀거리를 스스로 찾는 힘','2026-08-01'),
('M-E05','mid','weekend','가족 신발 가지런히 놓기','family',5,'weekly','review','정리된 현관','any',2,'내 것 너머를 챙기기 시작한다','2026-08-01'),
('M-E06','mid','weekend','소파 쿠션 털어 정리하기','family',3,'weekly','instant',NULL,'any',1,'주말 청소에서 한 몫을 맡는다','2026-08-01'),
('M-E07','mid','weekend','책상 서랍 한 칸 비우기','things',10,'weekly','review','치운 서랍 한 칸','any',2,'버릴 것과 둘 것을 스스로 가른다','2026-08-01'),
('M-E08','mid','weekend','도서관 삼십 분 다녀오기','study',30,'weekly','review','도서관에서 고른 책','any',3,'알아보러 몸을 옮기는 경험','2026-08-01'),
('M-E09','mid','weekend','용돈 기입장 한 줄 쓰기','money',5,'weekly','review','적은 기입장','evening',2,'돈을 숫자로 다루기 시작한다','2026-08-01'),
('M-E10','mid','weekend','우산 펴서 널어두기','things',2,'anytime','instant',NULL,'any',1,'날씨에 맞춰 스스로 움직인다','2026-08-01'),
('M-E11','mid','weekend','외식할 때 폰 안 보기','digital',60,'weekly','instant',NULL,'any',3,'같이 있는 자리에서 기기를 내려놓는다','2026-08-01'),
('M-E12','mid','weekend','재활용 그릇 씻어 내놓기','family',10,'weekly','review','씻은 플라스틱','any',2,'귀찮은 일을 끝까지 해내는 힘','2026-08-01'),
('M-E13','mid','weekend','자전거·킥보드 닦기','things',10,'weekly','review','닦은 자전거','any',2,'내 물건을 오래 쓰도록 손본다','2026-08-01'),
('M-E14','mid','weekend','식탁에 수저와 컵 놓기','family',5,'weekly','instant',NULL,'evening',2,'밥상 차리는 순서를 이해한다','2026-08-01'),
('M-E15','mid','weekend','입은 겉옷 세탁기에 넣기','things',3,'weekly','instant',NULL,'any',1,'내가 더럽힌 것을 내가 챙긴다','2026-08-01'),
('M-V01','mid','vacation','오전에 폰 아예 안 보기','digital',240,'daily','endday',NULL,'morning',3,'방학에 무너지기 쉬운 하루의 앞부분을 지킨다','2026-08-01'),
('M-V02','mid','vacation','점심 먹은 그릇 물에 담그기','family',2,'daily','instant',NULL,'any',1,'부모가 없을 때 뒷정리를 스스로','2026-08-01'),
('M-V11','mid','vacation','밥 퍼서 차려 먹기','family',10,'daily','review','차린 밥상','any',2,'해둔 밥을 퍼서 반찬 꺼내는 정도는 해야 한다','2026-08-01'),
('M-V03','mid','vacation','방학 계획표 하루치 체크','study',5,'daily','review','체크한 계획표','evening',2,'긴 시간을 스스로 나눠 쓴다','2026-08-01'),
('M-V04','mid','vacation','바깥에서 한 시간 놀기','outside',60,'daily','instant','앱 타이머','any',3,'집에만 있는 것을 막는다','2026-08-01'),
('M-V05','mid','vacation','부모님 오시면 마중 나가기','family',2,'daily','instant',NULL,'evening',1,'혼자 있던 시간을 끝맺는 인사','2026-08-01'),
('M-V06','mid','vacation','낮에 물 세 컵 마시기','body',3,'daily','instant',NULL,'any',1,'학교 정수기가 없는 동안 스스로 챙긴다','2026-08-01'),
('M-V07','mid','vacation','혼자 있을 때 문 잠그기','outside',1,'daily','instant',NULL,'any',1,'안전을 내가 챙긴다는 책임감','2026-08-01'),
('M-V08','mid','vacation','학원 갈 시간 스스로 챙기기','study',0,'daily','endday',NULL,'any',2,'전화 없이 시계를 보고 움직인다','2026-08-01'),
('M-V09','mid','vacation','방학 일기 쓰기','study',10,'weekly','review','쓴 일기장','evening',2,'학교가 없는 동안 기록을 남긴다','2026-08-01'),
('M-V10','mid','vacation','자기 전 내일 할 일 하나 정하기','mind',3,'daily','instant',NULL,'evening',1,'하루를 미리 그려보는 연습','2026-08-01'),
('M-P01','mid','patience','게임 끄기 전 삼 분 기다리기','digital',3,'daily','instant','앱 타이머','any',1,'갑자기 끊지 않고 스스로 마무리한다','2026-08-01'),
('M-P02','mid','patience','갖고 싶은 것 삼 일 생각하기','money',0,'anytime','endday',NULL,'any',3,'바로 사지 않고 사흘을 두고 본다','2026-08-01'),
('M-P03','mid','patience','화난 사람에게 십 분 말 안 걸기','mind',10,'anytime','instant',NULL,'any',2,'남의 마음을 읽고 기다려준다','2026-08-01'),
('M-P04','mid','patience','계산 줄에서 조용히 서 있기','outside',5,'anytime','instant',NULL,'any',2,'지루함을 견디는 힘','2026-08-01'),
('M-P05','mid','patience','영상 하나 끝까지 보기','digital',5,'daily','instant',NULL,'any',2,'넘기고 싶은 손가락을 멈춘다','2026-08-01');

-- ══════════ 초5~6 (45) ══════════
INSERT INTO missions (code,band,season,title,area,minutes,cycle,verify,verify_hint,slot,stars,why,created_at) VALUES
('H-W01','high','weekday','내일 준비물 혼자 챙기기','study',5,'daily','review','가방 속 준비물','evening',2,'간섭을 싫어하니 준비를 통째로 맡긴다','2026-08-01'),
('H-W02','high','weekday','저녁 먹고 식탁 정리하기','family',5,'daily','review','치운 식탁','evening',2,'집안일에서 한 사람 몫을 맡는다','2026-08-01'),
('H-W03','high','weekday','폰 삼십 분 끄고 쉬기','digital',30,'daily','instant','앱 타이머','any',3,'남이 시켜서가 아니라 스스로 멈춘다','2026-08-01'),
('H-W04','high','weekday','재활용 내다 버리기','family',10,'weekly','review','분리수거장','evening',2,'집 밖까지 활동 범위를 넓힌다','2026-08-01'),
('H-W05','high','weekday','스스로 정한 오늘 목표 하기','study',0,'daily','review','해낸 것','any',3,'내가 정한 것이라 반발이 없다','2026-08-01'),
('H-W06','high','weekday','쌀 씻어 밥솥에 안치기','family',10,'weekly','review','안친 밥솥','evening',2,'불을 쓰지 않고 밥상에 기여한다','2026-08-01'),
('H-W07','high','weekday','빨래 건조기에 옮기기','family',5,'weekly','instant',NULL,'any',2,'기계가 끝나는 때를 알고 이어서 한다','2026-08-01'),
('H-W08','high','weekday','바탕화면 파일 정리하기','digital',10,'weekly','review','정리된 바탕화면','any',2,'눈에 안 보이는 공간도 정리한다','2026-08-01'),
('H-W09','high','weekday','뉴스 하나 보고 세 줄 쓰기','study',10,'weekly','review','적은 노트','any',2,'세상 일을 내 말로 옮겨본다','2026-08-01'),
('H-W10','high','weekday','오늘 쓴 돈 적기','money',5,'daily','review','적은 기입장','evening',2,'쓴 돈을 눈으로 확인한다','2026-08-01'),
('H-W11','high','weekday','동생·반려동물 밥 챙기기','family',5,'daily','review','채운 밥그릇','any',2,'나보다 약한 것을 돌본다','2026-08-01'),
('H-W12','high','weekday','일어나서 이불 정리하기','things',5,'daily','review','정리된 침대','morning',2,'하루의 시작을 내 손으로 정돈한다','2026-08-01'),
('H-W13','high','weekday','수건 수거함에 넣기','body',1,'daily','instant',NULL,'evening',1,'몸 관리가 늘어나는 시기의 뒷정리','2026-08-01'),
('H-W14','high','weekday','확인해달라고 재촉 안 하기','mind',0,'daily','endday',NULL,'any',2,'결과가 올 때까지 기다리는 힘','2026-08-01'),
('H-W15','high','weekday','밤 열한 시 전에 눕기','body',0,'daily','endday',NULL,'evening',2,'잠이 모자라기 쉬운 나이의 마지노선','2026-08-01'),
('H-E01','high','weekend','내 신발 직접 빨기','things',20,'weekly','review','빨아 널어둔 신발','any',3,'손이 많이 가는 일을 혼자 해낸다','2026-08-01'),
('H-E02','high','weekend','내 방 청소기 돌리기','things',15,'weekly','review','치운 방','any',3,'기계를 다룰 수 있는 몸이 됐다','2026-08-01'),
('H-E03','high','weekend','이번 주 용돈 계획 세우기','money',10,'weekly','review','짠 계획','any',2,'쓰기 전에 미리 나눠본다','2026-08-01'),
('H-E04','high','weekend','냉장고 지난 것 찾아내기','family',10,'weekly','review','찾아낸 것','any',2,'가족 건강에 보탬이 된다는 실감','2026-08-01'),
('H-E05','high','weekend','도서관에서 책 골라오기','study',30,'weekly','review','빌려온 책','any',3,'무엇을 읽을지 스스로 고른다','2026-08-01'),
('H-E06','high','weekend','이번 주 한 일 돌아보기','mind',5,'weekly','review','체크한 화면','evening',2,'나를 한 발 떨어져 보는 힘','2026-08-01'),
('H-E07','high','weekend','차 안 쓰레기 비우기','family',10,'weekly','review','모은 쓰레기','any',2,'가족이 같이 쓰는 것을 챙긴다','2026-08-01'),
('H-E08','high','weekend','문제집 스스로 채점하기','study',15,'weekly','review','채점한 쪽','any',3,'틀린 것을 내가 확인한다','2026-08-01'),
('H-E09','high','weekend','변기 청소하기','family',15,'weekly','review','치운 변기','any',3,'제일 하기 싫은 일을 맡아본다','2026-08-01'),
('H-E10','high','weekend','안 입는 옷 세 벌 골라내기','things',10,'weekly','review','골라낸 옷','any',2,'몸이 자란 것을 알아채고 정리한다','2026-08-01'),
('H-E11','high','weekend','한 시간 기기 다 끄기','digital',60,'weekly','instant','앱 타이머','any',3,'스스로 끊어보는 시간','2026-08-01'),
('H-E12','high','weekend','신발장 내 신발 털기','things',10,'weekly','review','정리한 신발','any',2,'내 물건을 오래 쓰도록 손본다','2026-08-01'),
('H-E13','high','weekend','일요일 밤에 가방 다 싸기','study',10,'weekly','review','싼 가방','evening',2,'월요일을 미리 준비해 시작을 가볍게','2026-08-01'),
('H-E14','high','weekend','혼자 삼십 분 산책하기','outside',30,'weekly','instant','앱 타이머','any',3,'혼자 다니는 길을 만든다','2026-08-01'),
('H-E15','high','weekend','라면 끓여 먹기','family',20,'weekly','review','끓인 라면','any',3,'이 나이에 한 끼는 스스로 해결할 수 있어야 한다','2026-08-01'),
('H-E16','high','weekend','샌드위치·과일 차려 먹기','family',15,'weekly','review','차린 접시','any',2,'불 없이도 한 끼를 준비해본다','2026-08-01'),
('H-V01','high','vacation','정한 시간에 자고 일어나기','body',0,'daily','endday',NULL,'any',2,'자유가 늘어난 만큼 스스로 잡는다','2026-08-01'),
('H-V02','high','vacation','하루 예산 안에서 쓰기','money',0,'daily','endday',NULL,'any',3,'늘어난 시간의 충동 소비를 막는다','2026-08-01'),
('H-V03','high','vacation','나갈 때 가스 밸브 확인','outside',1,'daily','review','잠근 밸브','any',1,'집에 오래 있는 만큼 안전을 맡는다','2026-08-01'),
('H-V04','high','vacation','인터넷 강의 스스로 켜기','study',30,'daily','review','재생 중인 화면','any',3,'학원 밖에서 혼자 공부를 시작한다','2026-08-01'),
('H-V05','high','vacation','낮 열두 시까지 게임 안 하기','digital',240,'daily','endday',NULL,'morning',3,'하고 싶은 것을 뒤로 미뤄본다','2026-08-01'),
('H-V06','high','vacation','부모님께 안부 한 번 보내기','family',1,'daily','instant',NULL,'any',1,'혼자 있는 시간에 이어지는 끈','2026-08-01'),
('H-V07','high','vacation','이불 햇볕에 널기','things',10,'weekly','review','널어둔 이불','any',2,'낮 시간을 써서 내 잠자리를 챙긴다','2026-08-01'),
('H-V08','high','vacation','마트 심부름 다녀오기','family',30,'weekly','review','사온 것과 영수증','any',3,'계산과 바깥 활동을 함께 해낸다','2026-08-01'),
('H-V09','high','vacation','삼십 분 땀나게 움직이기','body',30,'daily','review','운동하고 난 얼굴','any',3,'몸이 크는 시기에 필요한 활동량','2026-08-01'),
('H-V10','high','vacation','학원까지 걸어가기','outside',20,'weekly','instant',NULL,'any',2,'차를 덜 타고 다리 힘을 기른다','2026-08-01'),
('H-V11','high','vacation','컵라면 혼자 만들어 먹기','family',10,'weekly','review','만든 컵라면','any',2,'뜨거운 물을 조심해서 다루는 연습','2026-08-01'),
('H-P01','high','patience','밥 오기 전에 간식 참기','mind',40,'anytime','instant',NULL,'any',2,'더 큰 것을 위해 작은 것을 미룬다','2026-08-01'),
('H-P02','high','patience','사고 싶은 것 주말까지 참기','money',0,'anytime','endday',NULL,'any',3,'며칠 두고 다시 생각해본다','2026-08-01'),
('H-P03','high','patience','화났을 때 오 분 뒤 보내기','mind',5,'anytime','instant','앱 타이머','any',2,'holding 화가 식은 뒤에 말한다','2026-08-01'),
('H-P04','high','patience','도장 일주일 안 쓰고 모으기','money',0,'weekly','endday',NULL,'any',3,'더 좋은 것을 위해 아껴둔다','2026-08-01'),
('H-P05','high','patience','상대 말 끝나고 삼 초 뒤 말하기','mind',1,'anytime','instant',NULL,'any',1,'말이 부딪히는 것을 줄인다','2026-08-01');

-- ══════════ 넣으면 안 되는 것 (20) ══════════
INSERT INTO mission_banned (title, reason) VALUES
('책 한 권 읽기 · 독후감 쓰기','원래 즐거운 일에 보상을 붙이면 보상이 끊길 때 전보다 덜 읽는다'),
('단원평가 백 점 맞기','결과에 보상을 걸면 거짓말·부정행위가 크게 는다'),
('형제와 안 싸우기','판정이 주관적이라 억울함이 생기고 시스템을 불신한다'),
('피아노·미술 삼십 분 연습','예술이 도장 받으려는 노동이 된다'),
('초1~4가 혼자 불 쓰기','저학년은 화상·화재 위험이 크다. 고학년은 「불을 써요」 표시를 달고 부모가 고르게 한다'),
('락스·세제로 청소하기','호흡기와 피부에 해로운 물질에 노출된다'),
('방 완벽하게 청소하기','「완벽」의 기준이 없어 좌절하고 결국 부모가 다시 한다'),
('부모님 말씀에 무조건 따르기','고학년의 자율성을 정면으로 누른다'),
('밥 남기지 않고 다 먹기','그날 컨디션을 무시해 식사에 강박이 생긴다'),
('친구에게 무조건 양보하기','「착한 일」의 기준이 어른 기분에 따라 달라진다'),
('영어 단어 하루 오십 개 외우기','난이도가 높아 실패가 쌓이면 아예 안 하게 된다'),
('며칠 연속 달성하기(스트릭)','끊기는 게 아까워 안 한 날도 눌러버린다'),
('형제보다 도장 많이 모으기','미션 난이도가 달라 개수 비교가 성립하지 않는다'),
('초1~4가 칼 쓰기','저학년은 손을 다칠 위험이 크다. 고학년은 부모 판단에 맡긴다'),
('무거운 쓰레기봉투 옮기기','몸에 무리가 가고 바깥 이동에 위험이 따른다'),
('사람들 앞에서 발표 잘하기','내성적인 아이에게 큰 불안을 주고 판정도 주관적이다'),
('울음 일 분 안에 그치기','감정을 억누르게 만들어 오히려 조절이 어려워진다'),
('하루 종일 화 안 내기','자연스러운 감정을 부정하는 비현실적인 목표'),
('오답 하나 없이 다 맞기','틀리면서 배우는 기회를 없애고 완벽주의를 만든다'),
('종교 활동 참석하기','믿음의 영역에 보상을 붙이면 스스로 받아들이는 것을 막는다');
